import type { RequestItem } from "@/features/properties/my-requests/types";

const HOUR_MS = 3_600_000;
const DAY_MS = 24 * HOUR_MS;

function daysAgo(days: number, hours = 0): string {
    return new Date(Date.now() - days * DAY_MS - hours * HOUR_MS).toISOString();
}

function hoursFromNow(hours: number): string {
    return new Date(Date.now() + hours * HOUR_MS).toISOString();
}

const IMAGES = [
    "/properties/1.jpg",
    "/properties/2.jpg",
    "/properties/3.jpg",
    "/properties/4.jpg",
    "/properties/5.jpg",
    "/properties/6.jpg",
] as const;

/**
 * Fixture set for the requests tracker. Covers every stage plus the edge
 * cases the UI has to handle: unseen by owner, expiring soon, and approved
 * but with no client attached yet.
 */
export const MOCK_REQUESTS: RequestItem[] = [
    {
        id: "req_042",
        propertyId: "pr_108",
        stage: "approved",
        title: "3 BHK Apartment in Vesu",
        configLabel: "3 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Vesu",
        city: "Surat",
        areaSqft: 1_650,
        bhk: 3,
        amountInr: 1_15_00_000,
        isRent: false,
        commissionPercent: 1.5,
        ownerName: "Rakesh Mehta",
        ownerPhoneDigits: "9825012345",
        ownerSeen: true,
        requestedAt: daysAgo(4),
        resolvedAt: daysAgo(2),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 0,
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 3,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[0],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(4) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(3, 4) },
            { key: "approved", label: "Owner accepted your request", at: daysAgo(2) },
        ],
    },
    {
        id: "req_039",
        propertyId: "pr_099",
        stage: "approved",
        title: "1 BHK Apartment in Pal",
        configLabel: "1 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Pal",
        city: "Surat",
        areaSqft: 620,
        bhk: 1,
        amountInr: 42_00_000,
        isRent: false,
        commissionPercent: 2,
        ownerName: "Sunita Desai",
        ownerPhoneDigits: "9898123456",
        ownerSeen: true,
        requestedAt: daysAgo(6),
        resolvedAt: daysAgo(1),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 1,
        brokerSlotsOpen: 0,
        brokerSlotsTotal: 2,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[1],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(6) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(5) },
            { key: "approved", label: "Owner accepted your request", at: daysAgo(1) },
        ],
    },
    {
        id: "req_055",
        propertyId: "pr_088",
        stage: "approved",
        title: "2 BHK Apartment in Piplod",
        configLabel: "2 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Piplod",
        city: "Surat",
        areaSqft: 1_100,
        bhk: 2,
        amountInr: 28_000,
        isRent: true,
        commissionPercent: 1,
        ownerName: "Imran Shaikh",
        ownerPhoneDigits: "9727098765",
        ownerSeen: true,
        requestedAt: daysAgo(9),
        resolvedAt: daysAgo(4),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 2,
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 4,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[2],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(9) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(8) },
            { key: "approved", label: "Owner accepted your request", at: daysAgo(4) },
        ],
    },
    {
        id: "req_047",
        propertyId: "pr_121",
        stage: "pending",
        title: "2 BHK Apartment in Adajan",
        configLabel: "2 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Adajan",
        city: "Surat",
        areaSqft: 980,
        bhk: 2,
        amountInr: 22_000,
        isRent: true,
        commissionPercent: 0,
        ownerName: "Bhavesh Patel",
        ownerSeen: false,
        requestedAt: daysAgo(6),
        resolvedAt: null,
        daysWaiting: 6,
        daysToExpiry: 1,
        expiresAt: hoursFromNow(9),
        clientsAttached: 0,
        brokerSlotsOpen: 2,
        brokerSlotsTotal: 3,
        remindersSent: 2,
        nudgedAt: daysAgo(3),
        imageSrc: IMAGES[3],
        timeline: [{ key: "sent", label: "You sent the request", at: daysAgo(6) }],
    },
    {
        id: "req_051",
        propertyId: "pr_130",
        stage: "pending",
        title: "4 BHK Villa in Vesu",
        configLabel: "4 BHK",
        propertyTypeLabel: "Villa",
        locality: "Vesu",
        city: "Surat",
        areaSqft: 3_200,
        bhk: 4,
        amountInr: 1_85_00_000,
        isRent: false,
        commissionPercent: 1.25,
        ownerName: "Nilesh Trivedi",
        ownerSeen: true,
        requestedAt: daysAgo(2),
        resolvedAt: null,
        daysWaiting: 2,
        daysToExpiry: 5,
        expiresAt: hoursFromNow(5 * 24 + 3),
        clientsAttached: 0,
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 2,
        remindersSent: 1,
        nudgedAt: daysAgo(1),
        imageSrc: IMAGES[4],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(2) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(1, 6) },
            { key: "nudged", label: "You sent a reminder", at: daysAgo(1) },
        ],
    },
    {
        id: "req_058",
        propertyId: "pr_141",
        stage: "pending",
        title: "Shop in Ring Road",
        configLabel: "Shop",
        propertyTypeLabel: "Shop",
        locality: "Ring Road",
        city: "Surat",
        areaSqft: 450,
        bhk: 0,
        amountInr: 98_00_000,
        isRent: false,
        commissionPercent: 2,
        ownerName: "Kirti Jariwala",
        ownerSeen: false,
        requestedAt: daysAgo(1),
        resolvedAt: null,
        daysWaiting: 1,
        daysToExpiry: 6,
        expiresAt: hoursFromNow(6 * 24 + 8),
        clientsAttached: 0,
        brokerSlotsOpen: 3,
        brokerSlotsTotal: 3,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[5],
        timeline: [{ key: "sent", label: "You sent the request", at: daysAgo(1) }],
    },
    {
        id: "req_033",
        propertyId: "pr_077",
        stage: "declined",
        title: "3 BHK Apartment in Athwa",
        configLabel: "3 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Athwa",
        city: "Surat",
        areaSqft: 1_450,
        bhk: 3,
        amountInr: 92_00_000,
        isRent: false,
        commissionPercent: 1,
        ownerName: "Paresh Kapadia",
        ownerSeen: true,
        requestedAt: daysAgo(12),
        resolvedAt: daysAgo(10),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 0,
        brokerSlotsOpen: 0,
        brokerSlotsTotal: 2,
        remindersSent: 0,
        nudgedAt: null,
        declineReason: "All broker slots were already filled",
        imageSrc: IMAGES[0],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(12) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(11) },
            { key: "declined", label: "Owner rejected your request", at: daysAgo(10) },
        ],
    },
    {
        id: "req_028",
        propertyId: "pr_064",
        stage: "declined",
        title: "Office in Udhna",
        configLabel: "Office",
        propertyTypeLabel: "Office",
        locality: "Udhna",
        city: "Surat",
        areaSqft: 1_800,
        bhk: 0,
        amountInr: 65_000,
        isRent: true,
        commissionPercent: 0,
        ownerName: "Meena Rathod",
        ownerSeen: true,
        requestedAt: daysAgo(18),
        resolvedAt: daysAgo(16),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 0,
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 3,
        remindersSent: 0,
        nudgedAt: null,
        declineReason: "Owner decided to hold the listing for now",
        imageSrc: IMAGES[1],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(18) },
            { key: "seen", label: "Owner opened your request", at: daysAgo(17) },
            { key: "declined", label: "Owner rejected your request", at: daysAgo(16) },
        ],
    },
    {
        id: "req_021",
        propertyId: "pr_052",
        stage: "expired",
        title: "2 BHK Apartment in Katargam",
        configLabel: "2 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Katargam",
        city: "Surat",
        areaSqft: 890,
        bhk: 2,
        amountInr: 56_00_000,
        isRent: false,
        commissionPercent: 1.5,
        ownerName: "Dinesh Vaghela",
        ownerSeen: false,
        requestedAt: daysAgo(24),
        resolvedAt: daysAgo(17),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 0,
        brokerSlotsOpen: 2,
        brokerSlotsTotal: 3,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[2],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(24) },
            { key: "expired", label: "Request expired, no reply", at: daysAgo(17) },
        ],
    },
    {
        id: "req_017",
        propertyId: "pr_045",
        stage: "withdrawn",
        title: "Plot in Sarthana",
        configLabel: "Plot",
        propertyTypeLabel: "Plot",
        locality: "Sarthana",
        city: "Surat",
        areaSqft: 2_400,
        bhk: 0,
        amountInr: 74_00_000,
        isRent: false,
        commissionPercent: 0,
        ownerName: "Alpesh Chauhan",
        ownerSeen: true,
        requestedAt: daysAgo(30),
        resolvedAt: daysAgo(28),
        daysWaiting: 0,
        daysToExpiry: null,
        expiresAt: null,
        clientsAttached: 0,
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 2,
        remindersSent: 0,
        nudgedAt: null,
        imageSrc: IMAGES[3],
        timeline: [
            { key: "sent", label: "You sent the request", at: daysAgo(30) },
            { key: "withdrawn", label: "You cancelled the request", at: daysAgo(28) },
        ],
    },
];

export const MOCK_REQUESTS_QUOTA = {
    limit: 10,
    used: 8,
    remaining: 2,
    resetsOn: new Date(Date.now() + 9 * DAY_MS).toISOString(),
};
