import type { InviteItem } from "@/features/properties/my-requests/invite-types";

const DAY_MS = 86_400_000;

function daysAgo(days: number, hours = 0): string {
    return new Date(Date.now() - days * DAY_MS - hours * 3_600_000).toISOString();
}

const IMAGES = [
    "/properties/1.jpg",
    "/properties/2.jpg",
    "/properties/3.jpg",
    "/properties/4.jpg",
    "/properties/5.jpg",
] as const;

/** Owners who picked this broker. Covers every stage the tab must render. */
export const MOCK_INVITES: InviteItem[] = [
    {
        id: "inv_004",
        propertyId: "pr_210",
        stage: "pending",
        title: "4 BHK Penthouse in Piplod",
        configLabel: "4 BHK",
        propertyTypeLabel: "Penthouse",
        locality: "Piplod",
        city: "Surat",
        areaSqft: 2_850,
        bhk: 4,
        amountInr: 2_40_00_000,
        isRent: false,
        commissionPercent: 2,
        ownerName: "Hitesh Ranpura",
        message: "Saw you closed two flats in our building. Can you take this one?",
        invitedAt: daysAgo(1),
        respondedAt: null,
        daysWaiting: 1,
        clientsAttached: 0,
        attachedClients: [],
        brokerSlotsOpen: 2,
        brokerSlotsTotal: 3,
        imageSrc: IMAGES[0],
    },
    {
        id: "inv_007",
        propertyId: "pr_218",
        stage: "pending",
        title: "2 BHK Apartment in Adajan",
        configLabel: "2 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Adajan",
        city: "Surat",
        areaSqft: 1_020,
        bhk: 2,
        amountInr: 32_000,
        isRent: true,
        commissionPercent: 1,
        ownerName: "Jigna Modi",
        message: null,
        invitedAt: daysAgo(4),
        respondedAt: null,
        daysWaiting: 4,
        clientsAttached: 0,
        attachedClients: [],
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 2,
        imageSrc: IMAGES[1],
    },
    {
        id: "inv_002",
        propertyId: "pr_205",
        stage: "accepted",
        title: "3 BHK Apartment in Vesu",
        configLabel: "3 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Vesu",
        city: "Surat",
        areaSqft: 1_580,
        bhk: 3,
        amountInr: 1_05_00_000,
        isRent: false,
        commissionPercent: 1.5,
        ownerName: "Vandana Joshi",
        ownerPhoneDigits: "9825055667",
        message: "My tenant is moving out next month.",
        invitedAt: daysAgo(11),
        respondedAt: daysAgo(10),
        daysWaiting: 0,
        clientsAttached: 0,
        attachedClients: [],
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 3,
        imageSrc: IMAGES[2],
    },
    {
        id: "inv_001",
        propertyId: "pr_201",
        stage: "declined",
        title: "Shop in Ghod Dod Road",
        configLabel: "Shop",
        propertyTypeLabel: "Shop",
        locality: "Ghod Dod Road",
        city: "Surat",
        areaSqft: 520,
        bhk: 0,
        amountInr: 1_10_00_000,
        isRent: false,
        commissionPercent: 0,
        ownerName: "Suresh Zaveri",
        message: null,
        invitedAt: daysAgo(20),
        respondedAt: daysAgo(18),
        daysWaiting: 0,
        clientsAttached: 0,
        attachedClients: [],
        brokerSlotsOpen: 0,
        brokerSlotsTotal: 2,
        imageSrc: IMAGES[3],
    },
    {
        id: "inv_003",
        propertyId: "pr_208",
        stage: "expired",
        title: "1 BHK Apartment in Katargam",
        configLabel: "1 BHK",
        propertyTypeLabel: "Apartment",
        locality: "Katargam",
        city: "Surat",
        areaSqft: 580,
        bhk: 1,
        amountInr: 38_00_000,
        isRent: false,
        commissionPercent: 1,
        ownerName: "Ramesh Gohil",
        message: null,
        invitedAt: daysAgo(30),
        respondedAt: daysAgo(23),
        daysWaiting: 0,
        clientsAttached: 0,
        attachedClients: [],
        brokerSlotsOpen: 1,
        brokerSlotsTotal: 2,
        imageSrc: IMAGES[4],
    },
];
