import type { OwnerListingItem } from "@/features/properties/owner-listings/types";

const LOCALITIES = ["Vesu", "Adajan", "Pal", "Athwa", "City Light", "Piplod"] as const;
const IMAGES = [
    "/properties/1.jpg",
    "/properties/2.jpg",
    "/properties/3.jpg",
    "/properties/4.jpg",
    "/properties/5.jpg",
    "/properties/6.jpg",
] as const;

/** Where each mock owner lives — pairs with OWNER_NAMES by index. */
const OWNER_LOCATIONS = [
    "Adajan, Surat",
    "Piplod, Surat",
    "Vesu, Surat",
    "Athwa, Surat",
    "Pal, Surat",
    "Katargam, Surat",
] as const;

const OWNER_NAMES = [
    "Rakesh Patel",
    "Nisha Desai",
    "Amit Shah",
    "Priya Mehta",
    "Karan Joshi",
    "Sneha Rao",
] as const;

type MockOwnerListingSeed = Omit<
    OwnerListingItem,
    | "id"
    | "imageSrc"
    | "imageSrcs"
    | "propertyTypeLabel"
    | "brokerSlotsTotal"
    | "brokerSlotsOpen"
    | "commissionPercent"
    | "ownerName"
    | "ownerAvatarUrl"
    | "ownerLocationLabel"
    | "photoCount"
    | "isNew"
    | "readyToMove"
>;

const PROPERTY_TYPES = ["apartment", "villa", "penthouse", "shop", "office", "plot"] as const;

const ENTRIES: MockOwnerListingSeed[] = [
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: 11_500_000,
        rentAmountInr: 45_000,
        areaSqft: 1250,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "5th floor",
        listedHoursAgo: 2,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Adajan",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 22_000,
        areaSqft: 890,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        detailLabel: "3rd floor",
        listedHoursAgo: 26,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: true,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Pal",
        city: "Surat",
        saleAmountInr: 8_500_000,
        rentAmountInr: null,
        areaSqft: 1180,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        detailLabel: "Green Park Society",
        listedHoursAgo: 52,
        brokerRequestCount: 3,
        hasRequested: true,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Piplod",
        city: "Surat",
        saleAmountInr: 1_85_00_000,
        rentAmountInr: null,
        areaSqft: 2100,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "River view",
        listedHoursAgo: 8,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 18_500,
        areaSqft: 950,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 120,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Athwa",
        city: "Surat",
        saleAmountInr: 72_00_000,
        rentAmountInr: 28_000,
        areaSqft: 1320,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        detailLabel: "Shanti Niketan",
        listedHoursAgo: 36,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "Adajan",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 12_500,
        areaSqft: 520,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 4,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "City Light",
        city: "Surat",
        saleAmountInr: 95_00_000,
        rentAmountInr: 38_000,
        areaSqft: 1450,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 72,
        brokerRequestCount: 4,
        hasRequested: false,
        isBookmarked: true,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Pal",
        city: "Surat",
        saleAmountInr: 58_00_000,
        rentAmountInr: null,
        areaSqft: 980,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 18,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: 2_10_00_000,
        rentAmountInr: null,
        areaSqft: 2400,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        detailLabel: "Penthouse",
        listedHoursAgo: 96,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Piplod",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 25_000,
        areaSqft: 1150,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 14,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Athwa",
        city: "Surat",
        saleAmountInr: 42_00_000,
        rentAmountInr: null,
        areaSqft: 860,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 200,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Adajan",
        city: "Surat",
        saleAmountInr: 68_00_000,
        rentAmountInr: null,
        areaSqft: 1280,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 44,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 9_500,
        areaSqft: 480,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 6,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "City Light",
        city: "Surat",
        saleAmountInr: 1_45_00_000,
        rentAmountInr: 55_000,
        areaSqft: 1980,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 28,
        brokerRequestCount: 3,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Pal",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 16_000,
        areaSqft: 820,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 10,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Piplod",
        city: "Surat",
        saleAmountInr: 1_05_00_000,
        rentAmountInr: null,
        areaSqft: 1520,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 60,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: 62_00_000,
        rentAmountInr: null,
        areaSqft: 910,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 22,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Athwa",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 20_500,
        areaSqft: 1200,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 48,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Adajan",
        city: "Surat",
        saleAmountInr: 1_72_00_000,
        rentAmountInr: null,
        areaSqft: 2250,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 80,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "City Light",
        city: "Surat",
        saleAmountInr: 35_00_000,
        rentAmountInr: null,
        areaSqft: 560,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 15,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Pal",
        city: "Surat",
        saleAmountInr: 78_00_000,
        rentAmountInr: 32_000,
        areaSqft: 1380,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 5,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Piplod",
        city: "Surat",
        saleAmountInr: null,
        rentAmountInr: 19_000,
        areaSqft: 880,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 30,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Vesu",
        city: "Surat",
        saleAmountInr: 88_00_000,
        rentAmountInr: null,
        areaSqft: 1420,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "Lake view",
        listedHoursAgo: 12,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
];

export const MOCK_OWNER_LISTINGS: OwnerListingItem[] = ENTRIES.map((entry, index) => {
    const photoCount = 4 + (index % 5);
    const imageSrcs = Array.from(
        { length: photoCount },
        (_, photoIndex) => IMAGES[(index + photoIndex) % IMAGES.length]!,
    );

    return {
        ...entry,
        state: "Gujarat",
        country: "India",
        id: `ol_${String(index + 1).padStart(3, "0")}`,
        imageSrc: imageSrcs[0]!,
        imageSrcs,
        propertyTypeLabel: PROPERTY_TYPES[index % PROPERTY_TYPES.length]!,
        brokerSlotsTotal: 3,
        brokerSlotsOpen: Math.max(0, 3 - entry.brokerRequestCount),
        commissionPercent: index % 4 === 0 ? 0 : index % 3 === 0 ? 2.5 : 2,
        ownerName: OWNER_NAMES[index % OWNER_NAMES.length]!,
        ownerUserId: `owner-user-${(index % OWNER_NAMES.length) + 1}`,
        ownerLocationLabel: OWNER_LOCATIONS[index % OWNER_LOCATIONS.length]!,
        photoCount,
        isNew: entry.listedHoursAgo <= 7 * 24,
        readyToMove: index % 5 < 2,
    };
});

export const OWNER_LISTING_LOCALITIES = [...LOCALITIES];
