import type { OwnerListingItem } from "@/features/properties/owner-listings/types";

const LOCALITIES = ["Vesu", "Adajan", "Pal", "Athwa", "City Light", "Piplod"] as const;
const IMAGES = [
    "/properties/1.jpg",
    "/properties/2.jpg",
    "/properties/3.jpg",
    "/properties/4.jpg",
    "/properties/5.jpg",
    "/properties/6.jpg",
] as const;

const OWNER_NAMES = [
    "Rakesh Patel",
    "Nisha Desai",
    "Amit Shah",
    "Priya Mehta",
    "Karan Joshi",
    "Sneha Rao",
] as const;

type MockOwnerListingSeed = Omit<
    OwnerListingItem,
    | "id"
    | "imageSrc"
    | "propertyTypeLabel"
    | "brokerSlotsTotal"
    | "brokerSlotsOpen"
    | "commissionPercent"
    | "ownerName"
    | "ownerAvatarUrl"
    | "photoCount"
    | "isNew"
    | "readyToMove"
>;

const PROPERTY_TYPES = ["apartment", "villa", "penthouse", "shop", "office", "plot"] as const;

const ENTRIES: MockOwnerListingSeed[] = [
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Vesu",
        city: "Surat",
        amountInr: 11_500_000,
        isRent: false,
        areaSqft: 1250,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "5th floor",
        listedHoursAgo: 2,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Adajan",
        city: "Surat",
        amountInr: 22_000,
        isRent: true,
        areaSqft: 890,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        detailLabel: "3rd floor",
        listedHoursAgo: 26,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: true,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Pal",
        city: "Surat",
        amountInr: 8_500_000,
        isRent: false,
        areaSqft: 1180,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        detailLabel: "Green Park Society",
        listedHoursAgo: 52,
        brokerRequestCount: 3,
        hasRequested: true,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Piplod",
        city: "Surat",
        amountInr: 1_85_00_000,
        isRent: false,
        areaSqft: 2100,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "River view",
        listedHoursAgo: 8,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Vesu",
        city: "Surat",
        amountInr: 18_500,
        isRent: true,
        areaSqft: 950,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 120,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Athwa",
        city: "Surat",
        amountInr: 72_00_000,
        isRent: false,
        areaSqft: 1320,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        detailLabel: "Shanti Niketan",
        listedHoursAgo: 36,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "Adajan",
        city: "Surat",
        amountInr: 12_500,
        isRent: true,
        areaSqft: 520,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 4,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "City Light",
        city: "Surat",
        amountInr: 95_00_000,
        isRent: false,
        areaSqft: 1450,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 72,
        brokerRequestCount: 4,
        hasRequested: false,
        isBookmarked: true,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Pal",
        city: "Surat",
        amountInr: 58_00_000,
        isRent: false,
        areaSqft: 980,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 18,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Vesu",
        city: "Surat",
        amountInr: 2_10_00_000,
        isRent: false,
        areaSqft: 2400,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        detailLabel: "Penthouse",
        listedHoursAgo: 96,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Piplod",
        city: "Surat",
        amountInr: 25_000,
        isRent: true,
        areaSqft: 1150,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 14,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Athwa",
        city: "Surat",
        amountInr: 42_00_000,
        isRent: false,
        areaSqft: 860,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 200,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Adajan",
        city: "Surat",
        amountInr: 68_00_000,
        isRent: false,
        areaSqft: 1280,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 44,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "Vesu",
        city: "Surat",
        amountInr: 9_500,
        isRent: true,
        areaSqft: 480,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 6,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "City Light",
        city: "Surat",
        amountInr: 1_45_00_000,
        isRent: false,
        areaSqft: 1980,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 28,
        brokerRequestCount: 3,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Pal",
        city: "Surat",
        amountInr: 16_000,
        isRent: true,
        areaSqft: 820,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 10,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Piplod",
        city: "Surat",
        amountInr: 1_05_00_000,
        isRent: false,
        areaSqft: 1520,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 60,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Vesu",
        city: "Surat",
        amountInr: 62_00_000,
        isRent: false,
        areaSqft: 910,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 22,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Athwa",
        city: "Surat",
        amountInr: 20_500,
        isRent: true,
        areaSqft: 1200,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 48,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "4 BHK",
        bhk: 4,
        locality: "Adajan",
        city: "Surat",
        amountInr: 1_72_00_000,
        isRent: false,
        areaSqft: 2250,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 80,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "1 BHK",
        bhk: 1,
        locality: "City Light",
        city: "Surat",
        amountInr: 35_00_000,
        isRent: false,
        areaSqft: 560,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        listedHoursAgo: 15,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Pal",
        city: "Surat",
        amountInr: 78_00_000,
        isRent: false,
        areaSqft: 1380,
        furnishingLabel: "Unfurnished",
        furnishing: "unfurnished",
        listedHoursAgo: 5,
        brokerRequestCount: 0,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "2 BHK",
        bhk: 2,
        locality: "Piplod",
        city: "Surat",
        amountInr: 19_000,
        isRent: true,
        areaSqft: 880,
        furnishingLabel: "Furnished",
        furnishing: "furnished",
        listedHoursAgo: 30,
        brokerRequestCount: 2,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
    {
        configLabel: "3 BHK",
        bhk: 3,
        locality: "Vesu",
        city: "Surat",
        amountInr: 88_00_000,
        isRent: false,
        areaSqft: 1420,
        furnishingLabel: "Semi-furnished",
        furnishing: "semi",
        detailLabel: "Lake view",
        listedHoursAgo: 12,
        brokerRequestCount: 1,
        hasRequested: false,
        isBookmarked: false,
        status: "active",
    },
];

export const MOCK_OWNER_LISTINGS: OwnerListingItem[] = ENTRIES.map((entry, index) => ({
    ...entry,
    id: `ol_${String(index + 1).padStart(3, "0")}`,
    imageSrc: IMAGES[index % IMAGES.length]!,
    propertyTypeLabel: PROPERTY_TYPES[index % PROPERTY_TYPES.length]!,
    brokerSlotsTotal: 3,
    brokerSlotsOpen: Math.max(0, 3 - entry.brokerRequestCount),
    commissionPercent: index % 4 === 0 ? 0 : index % 3 === 0 ? 2.5 : 2,
    ownerName: OWNER_NAMES[index % OWNER_NAMES.length]!,
    photoCount: 4 + (index % 5),
    isNew: entry.listedHoursAgo <= 24,
    readyToMove: index % 5 < 2,
}));

export const OWNER_LISTING_LOCALITIES = [...LOCALITIES];
