import type { ClientItem } from "@/features/clients/types";

const DAY_MS = 86_400_000;

function daysAgo(days: number): string {
    return new Date(Date.now() - days * DAY_MS).toISOString();
}

/** The broker's own book of buyers, for the attach-to-property picker. */
export const MOCK_CLIENTS: ClientItem[] = [
    {
        id: "cl_001",
        name: "Ankit Shah",
        phoneDigits: "9825011223",
        email: null,
        lookingFor: "buy",
        propertyKind: "apartment",
        preferredLocalities: ["Vesu", "Piplod"],
        budgetMinInr: null,
        budgetMaxInr: 1_30_00_000,
        bhk: 3,
        source: "referral",
        notes: null,
        lastContactedAt: daysAgo(2),
        attachedPropertyCount: 2,
        documents: [],
    },
    {
        id: "cl_002",
        name: "Priya Nair",
        phoneDigits: "9898044556",
        email: null,
        lookingFor: "buy",
        propertyKind: "apartment",
        preferredLocalities: ["Vesu", "Athwa"],
        budgetMinInr: null,
        budgetMaxInr: 1_20_00_000,
        bhk: 3,
        source: "portal",
        notes: null,
        lastContactedAt: daysAgo(5),
        attachedPropertyCount: 1,
        documents: [],
    },
    {
        id: "cl_003",
        name: "Mohit Agarwal",
        phoneDigits: "9727066778",
        email: null,
        lookingFor: "buy",
        propertyKind: "apartment",
        preferredLocalities: ["Adajan", "Pal"],
        budgetMinInr: null,
        budgetMaxInr: 60_00_000,
        bhk: 2,
        source: "walk_in",
        notes: null,
        lastContactedAt: daysAgo(1),
        attachedPropertyCount: 0,
        documents: [],
    },
    {
        id: "cl_004",
        name: "Sneha Bhatt",
        phoneDigits: "9016077889",
        email: null,
        lookingFor: "rent",
        propertyKind: "apartment",
        preferredLocalities: ["Piplod", "Vesu"],
        budgetMinInr: null,
        budgetMaxInr: 35_000,
        bhk: 2,
        source: "referral",
        notes: null,
        lastContactedAt: daysAgo(9),
        attachedPropertyCount: 3,
        documents: [],
    },
    {
        id: "cl_005",
        name: "Rajesh Kumar",
        phoneDigits: "9825099001",
        email: null,
        lookingFor: "buy",
        propertyKind: "villa",
        preferredLocalities: ["Vesu"],
        budgetMinInr: null,
        budgetMaxInr: 2_00_00_000,
        bhk: 4,
        source: "repeat",
        notes: null,
        lastContactedAt: daysAgo(14),
        attachedPropertyCount: 1,
        documents: [],
    },
    {
        id: "cl_006",
        name: "Farida Contractor",
        phoneDigits: "9898122334",
        email: null,
        lookingFor: "buy",
        propertyKind: "apartment",
        preferredLocalities: ["Athwa", "Ghod Dod Road"],
        budgetMinInr: null,
        budgetMaxInr: 95_00_000,
        bhk: 3,
        source: "social",
        notes: null,
        lastContactedAt: null,
        attachedPropertyCount: 0,
        documents: [],
    },
    {
        id: "cl_007",
        name: "Deepak Solanki",
        phoneDigits: "9727144556",
        email: null,
        lookingFor: "rent",
        propertyKind: "apartment",
        preferredLocalities: ["Adajan"],
        budgetMinInr: null,
        budgetMaxInr: 25_000,
        bhk: 2,
        source: "walk_in",
        notes: null,
        lastContactedAt: daysAgo(4),
        attachedPropertyCount: 2,
        documents: [],
    },
    {
        id: "cl_008",
        name: "Nisha Patel",
        phoneDigits: "9016155667",
        email: null,
        lookingFor: "buy",
        propertyKind: "plot",
        preferredLocalities: ["Katargam", "Ring Road"],
        budgetMinInr: null,
        budgetMaxInr: 75_00_000,
        bhk: null,
        source: "other",
        notes: null,
        lastContactedAt: daysAgo(21),
        attachedPropertyCount: 0,
        documents: [],
    },
];

/**
 * Which buyers are already on which property, keyed by property id. Mirrors
 * what the API would return alongside the request.
 */
export const MOCK_PROPERTY_CLIENTS: Record<string, string[]> = {
    pr_099: ["cl_002"],
    pr_088: ["cl_004", "cl_007"],
};
